
//自动生成，请勿手动修改
using UnityEditor;
using System.Reflection;
using UnityEngine;

public static class AutoGeneratedMenus
{

    [MenuItem("Tools/OdinEditorSample/MenuTreeSample")]
    public static void Menu_MenuTreeSample_OpenWindow()
    {
        var type = typeof(MenuTreeSample);
        var method = type.GetMethod("OpenWindow", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
        if (method == null)
        {
            Debug.LogError("未能找到方法 MenuTreeSample.OpenWindow");
            return;
        }
        method.Invoke(null, null);
    }


    [MenuItem("Tools/OdinEditorSample/TextureSample")]
    public static void Menu_TextureSample_OpenWindow()
    {
        var type = typeof(TextureSample);
        var method = type.GetMethod("OpenWindow", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
        if (method == null)
        {
            Debug.LogError("未能找到方法 TextureSample.OpenWindow");
            return;
        }
        method.Invoke(null, null);
    }


    [MenuItem("Tools/OdinEditorSample/SimpleOdinMultiWindow")]
    public static void Menu_SimpleOdinMultiWindow_OpenWindow()
    {
        var type = typeof(SimpleOdinMultiWindow);
        var method = type.GetMethod("OpenWindow", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
        if (method == null)
        {
            Debug.LogError("未能找到方法 SimpleOdinMultiWindow.OpenWindow");
            return;
        }
        method.Invoke(null, null);
    }


    [MenuItem("Tools/OdinEditorSample/SimpleOdinWindow")]
    public static void Menu_SimpleOdinWindow_OpenWindow()
    {
        var type = typeof(SimpleOdinWindow);
        var method = type.GetMethod("OpenWindow", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
        if (method == null)
        {
            Debug.LogError("未能找到方法 SimpleOdinWindow.OpenWindow");
            return;
        }
        method.Invoke(null, null);
    }


}
