using System;
using System.IO;
using System.Text;
using Core;
using LDtkUnity;
using LDtkUnity.Editor;
using UnityEditor;
using UnityEngine;

namespace GameMain.Editor
{
    public class LDtkIdentifiersProcessor : LDtkPostprocessor
    {
        public override int GetPostprocessOrder() => 1;

        protected override void OnPostprocessProject(GameObject root)
        {
            if (!root.TryGetComponent<LDtkComponentProject>(out var projectComponent))
            {
                return;
            }

            LdtkJson json = projectComponent.Json.FromJson;
            if (json == null)
            {
                return;
            }

            GenerateIdentifiersFile(json);
        }

        private void GenerateIdentifiersFile(LdtkJson json)
        {
            StringBuilder sb = new();
            sb.AppendLine(
                "// This file is auto-generated by LDtkIdentifiersProcessor. Do not edit manually."
            );
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("");
            sb.AppendLine("namespace GameMain.RunTime");
            sb.AppendLine("{");
            sb.AppendLine("// csharpier-ignore-start");
            sb.AppendLine("    public static class LDtkIdentifiers");
            sb.AppendLine("    {");

            if (json.Defs != null)
            {
                // Layer Identifiers
                if (json.Defs.Layers != null && json.Defs.Layers.Length > 0)
                {
                    sb.AppendLine("        // Layer Identifiers");
                    foreach (LayerDefinition layer in json.Defs.Layers)
                    {
                        string comment = !string.IsNullOrEmpty(layer.Doc) ? $" // {layer.Doc}" : "";
                        sb.AppendLine(
                            $"        public const string {layer.Identifier} = \"{layer.Identifier}\";{comment}"
                        );
                    }
                    sb.AppendLine("");
                }

                // Entity Identifiers
                if (json.Defs.Entities != null && json.Defs.Entities.Length > 0)
                {
                    sb.AppendLine("        // Entity Identifiers");
                    foreach (EntityDefinition entity in json.Defs.Entities)
                    {
                        string comment = !string.IsNullOrEmpty(entity.Doc)
                            ? $" // {entity.Doc}"
                            : "";
                        sb.AppendLine(
                            $"        public const string {entity.Identifier} = \"{entity.Identifier}\";{comment}"
                        );
                    }
                    sb.AppendLine("");
                }

                // Enum Identifiers
                if (json.Defs.Enums != null && json.Defs.Enums.Length > 0)
                {
                    sb.AppendLine("        // Enum Identifiers");
                    foreach (EnumDefinition @enum in json.Defs.Enums)
                    {
                        sb.AppendLine(
                            $"        public const string Enum_{@enum.Identifier} = \"{@enum.Identifier}\";"
                        );
                    }
                    sb.AppendLine("");
                }

                // External Enum Identifiers
                if (json.Defs.ExternalEnums != null && json.Defs.ExternalEnums.Length > 0)
                {
                    sb.AppendLine("        // External Enum Identifiers");
                    foreach (EnumDefinition @enum in json.Defs.ExternalEnums)
                    {
                        sb.AppendLine(
                            $"        public const string Enum_{@enum.Identifier} = \"{@enum.Identifier}\";"
                        );
                    }
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("// csharpier-ignore-end");
            sb.AppendLine("}");

            string filePath =
                "Assets/GameMain/Scripts/RunTime/GameCoreSystems/LevelManager/LDtkIdentifiers.cs";

            // Only write if changed to avoid unnecessary re-imports
            if (File.Exists(filePath))
            {
                string existingContent = File.ReadAllText(filePath);
                if (existingContent == sb.ToString())
                {
                    return;
                }
            }

            try
            {
                string directory = Path.GetDirectoryName(filePath);
                if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }
                File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
            }
            catch (Exception e)
            {
                CLogger.LogError(
                    $"Failed to write LDtkIdentifiers.cs: {e}",
                    LogTag.LDtkIdentifiersProcessor
                );
                return;
            }

            AssetDatabase.Refresh();
        }
    }
}
