using System;

using Scriban;

namespace Core
{
    public class CodePrefix
    {
        public static class CodeCommentTemplate
        {
            public static string GetAutoGeneratedComment(
                string toolName = "AutoCodeGen",
                DateTime? generationTime = null
            )
            {
                var template = Template.Parse(CommentTemplate);

                var context = new
                {
                    generation_time = (generationTime ?? DateTime.Now).ToString(
                        "yyyy-MM-dd HH:mm:ss"
                    ),
                    tool_name = toolName,
                };

                return template.Render(context);
            }
        }

        private const string CommentTemplate =
            @"
// <auto-generated>
// This code was generated automatically.
// DO NOT modify this file manually.
// Generation Time: {{ generation_time }}
// Tool: {{ tool_name }}
// </auto-generated>
";
    }
}
