using System;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEditor;
using UnityEngine;

[AttributeUsage(AttributeTargets.Method)]
public class AutoOdinWindowMenuAttribute : Attribute
{
    public string CustomName { get; }

    public AutoOdinWindowMenuAttribute(string customName = null)
    {
        CustomName = customName;
    }
}

public static class AutoMenuGenerator
{
    // 1. 可配置代码生成目录（推荐使用 Editor 下的某个子目录）
    private const string OutputFolder = "Assets/Demos/OdinEditorSample/Editor/AutoGeneratedMenus";
    private const string OutputFileName = "AutoGeneratedMenus.cs";

    [MenuItem("Tools/OdinEditorSample/🛠️ 重新生成菜单")]
    public static void GenerateMenus()
    {
        var allMethods = AppDomain
            .CurrentDomain.GetAssemblies()
            .Where(asm => !asm.FullName.StartsWith("Unity") && !asm.FullName.StartsWith("System")) // 加速过滤
            .SelectMany(a =>
            {
                try
                {
                    return a.GetTypes();
                }
                catch
                {
                    return new Type[0];
                }
            })
            .SelectMany(t =>
                t.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static)
            )
            .Where(m => m.GetCustomAttribute<AutoOdinWindowMenuAttribute>() != null)
            .ToList();

        if (!allMethods.Any())
        {
            Debug.LogWarning("⚠️ 未找到任何带 [AutoOdinWindowMenu] 的静态方法。");
            return;
        }

        if (!Directory.Exists(OutputFolder))
            Directory.CreateDirectory(OutputFolder);

        string filePath = Path.Combine(OutputFolder, OutputFileName);

        using (StreamWriter writer = new StreamWriter(filePath, false))
        {
            writer.WriteLine("// 自动生成，请勿手动修改");
            writer.WriteLine("using UnityEditor;");
            writer.WriteLine("using System.Reflection;");
            writer.WriteLine("using UnityEngine;");
            writer.WriteLine();
            writer.WriteLine("public static class AutoGeneratedMenus");
            writer.WriteLine("{");

            foreach (var method in allMethods)
            {
                var attr = method.GetCustomAttribute<AutoOdinWindowMenuAttribute>();
                string typeFullName = method.DeclaringType.FullName.Replace('+', '.'); // 嵌套类支持
                string methodName = method.Name;
                string menuName = attr.CustomName ?? methodName;

                // Unity 菜单路径
                string menuPath = $"Tools/OdinEditorSample/{method.DeclaringType.Name}";

                // 生成唯一函数名（防止重复）
                string uniqueFunctionName = $"Menu_{Sanitize(typeFullName)}_{methodName}";

                writer.WriteLine($"    [MenuItem(\"{menuPath}\")]");
                writer.WriteLine($"    public static void {uniqueFunctionName}()");
                writer.WriteLine("    {");

                // 用反射调用，避免 private static 无法直接访问
                writer.WriteLine($"        var type = typeof({typeFullName});");
                writer.WriteLine(
                    $"        var method = type.GetMethod(\"{methodName}\", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);"
                );
                writer.WriteLine("        if (method == null)");
                writer.WriteLine("        {");
                writer.WriteLine(
                    $"            Debug.LogError(\"未能找到方法 {typeFullName}.{methodName}\");"
                );
                writer.WriteLine("            return;");
                writer.WriteLine("        }");
                writer.WriteLine("        method.Invoke(null, null);");

                writer.WriteLine("    }");
                writer.WriteLine();
            }

            writer.WriteLine("}");
        }

        AssetDatabase.Refresh();
        Debug.Log($"✅ 已生成自动菜单代码，共 {allMethods.Count} 个项。位置：{filePath}");
    }

    // 用于将类名中的非法字符替换成合法的函数名（如命名空间中的.）
    private static string Sanitize(string name)
    {
        return name.Replace('.', '_').Replace('+', '_');
    }
}
