using System;
using System.IO;
using System.Linq;
using System.Reflection;
using Scriban;
using UnityEditor;
using UnityEngine;

[AttributeUsage(AttributeTargets.Method)]
public class AutoOdinWindowMenuAttribute : Attribute
{
    public string CustomName { get; }

    public AutoOdinWindowMenuAttribute(string customName = null)
    {
        CustomName = customName;
    }
}

public static class AutoMenuGenerator
{
    [MenuItem("Tools/OdinEditorSample/🛠️ 重新生成菜单")]
    public static void GenerateMenus()
    {
        var allMethods = AppDomain
            .CurrentDomain.GetAssemblies()
            .Where(asm => !asm.FullName.StartsWith("Unity") && !asm.FullName.StartsWith("System")) // 加速过滤
            .SelectMany(a =>
            {
                try
                {
                    return a.GetTypes();
                }
                catch
                {
                    return new Type[0];
                }
            })
            .SelectMany(t =>
                t.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static)
            )
            .Where(m => m.GetCustomAttribute<AutoOdinWindowMenuAttribute>() != null)
            .ToList();

        if (!allMethods.Any())
        {
            Debug.LogWarning("⚠️ 未找到任何带 [AutoOdinWindowMenu] 的静态方法。");
            return;
        }

        if (!Directory.Exists(OutputFolder))
            Directory.CreateDirectory(OutputFolder);

        var methodsForTemplate = allMethods
            .Select(method =>
            {
                var attr = method.GetCustomAttribute<AutoOdinWindowMenuAttribute>();
                string typeFullName = method.DeclaringType.FullName.Replace('+', '.');
                string methodName = method.Name;
                string menuPath = $"Tools/OdinEditorSample/{method.DeclaringType.Name}";
                string uniqueFunctionName = $"Menu_{Sanitize(typeFullName)}_{methodName}";

                return new
                {
                    type_name = method.DeclaringType.Name,
                    type_full_name = typeFullName,
                    method_name = methodName,
                    unique_function_name = uniqueFunctionName,
                    menu_path = menuPath,
                    custom_name = attr.CustomName ?? methodName,
                };
            })
            .ToList();

        var template = Template.Parse(AutoMenuGenerator.templateText);
        string result = template.Render(
            new { methods = methodsForTemplate },
            memberRenamer: member => member.Name
        );

        string filePath = Path.Combine(OutputFolder, OutputFileName);
        File.WriteAllText(filePath, result);

        AssetDatabase.Refresh();
        Debug.Log($"✅ 已生成自动菜单代码，共 {allMethods.Count} 个项。位置：{filePath}");
    }

    private static string Sanitize(string name)
    {
        return name.Replace('.', '_').Replace('+', '_');
    }

    private const string OutputFolder = "Assets/Demos/OdinEditorSample/Editor/AutoGeneratedMenus";
    private const string OutputFileName = "AutoGeneratedMenus.cs";

    private const
    // 这里用硬编码模板字符串，你也可以从文件加载
    string templateText =
        @"
自动生成，请勿手动修改
using UnityEditor;
using System.Reflection;
using UnityEngine;

public static class AutoGeneratedMenus
{
{{ for method in methods }}
    [MenuItem(""{{ method.menu_path }}"")]
    public static void {{ method.unique_function_name }}()
    {
        var type = typeof({{ method.type_full_name }});
        var method = type.GetMethod(""{{ method.method_name }}"", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
        if (method == null)
        {
            Debug.LogError(""未能找到方法 {{ method.type_full_name }}.{{ method.method_name }}"");
            return;
        }
        method.Invoke(null, null);
    }

{{ end }}
}
";
}
