// This file is auto-generated by LDtkIdentifiersProcessor. Do not edit manually.
// csharpier-ignore-start
using UnityEngine;

namespace GameMain.RunTime
{
    public static class LDtkIdentifiers
    {
        // Layer Identifiers
        public const string AutoLayer_Zone = "AutoLayer_Zone";
        public const string AutoTiles_Wall_A = "AutoTiles_Wall_A"; // 自动绘制的瓦片层, 包含地面、平台等
        public const string AutoTiles_Wall_B = "AutoTiles_Wall_B"; // 自动绘制的瓦片层, 包含地面、平台等
        public const string AutoTiles_BG_A = "AutoTiles_BG_A"; // 自动绘制的瓦片层, 包含地面、平台等
        public const string AutoTiles_BG_B = "AutoTiles_BG_B"; // 自动绘制的瓦片层, 包含地面、平台等
        public const string ManualTiles = "ManualTiles"; // 手动绘制的瓦片层, 包含装饰性元素
        public const string Entities = "Entities"; // 实体层, 包含玩家、敌人、道具等
        public const string LogicMap = "LogicMap"; // 逻辑地图层, 0: Wall,
        public const string BGMap = "BGMap";

        // Entity Identifiers
        public const string Ae_SavePoint = "Ae_SavePoint"; // Save point, where store player's level progress.
        public const string Ae_MovePlatformer = "Ae_MovePlatformer";
        public const string Ae_MovePlatformerPathPoint = "Ae_MovePlatformerPathPoint";
        public const string Ae_CameraOverrideArea = "Ae_CameraOverrideArea";
        public const string Ae_SnakeHoney = "Ae_SnakeHoney";
        public const string Ae_SnakeDoor = "Ae_SnakeDoor";
        public const string Ae_LevelClearPoint = "Ae_LevelClearPoint";
        public const string Ae_Mat_Checkpoint = "Ae_Mat_Checkpoint";
        public const string Ae_Mat_Bee = "Ae_Mat_Bee";

        // Enum Identifiers
        public const string Enum_CameraMode = "CameraMode";

    }
}
// csharpier-ignore-end
