// This file is auto-generated by LDtkIdentifiersProcessor. Do not edit manually.
using UnityEngine;

namespace GameMain.RunTime
{
    // csharpier-ignore-start
    public static class LDtkIdentifiers
    {
        // Layer Identifiers
        public const string AutoLayer_MineDanger = "AutoLayer_MineDanger";
        public const string AutoLayer_MinePole = "AutoLayer_MinePole";
        public const string AutoLayer_MineWall = "AutoLayer_MineWall";
        public const string AutoLayer_Zone = "AutoLayer_Zone";
        public const string AutoTiles_Wall_A = "AutoTiles_Wall_A"; // 自动绘制的瓦片层, 包含地面、平台等
        public const string AutoTiles_Wall_B = "AutoTiles_Wall_B"; // 自动绘制的瓦片层, 包含地面、平台等
        public const string Entities = "Entities"; // 实体层, 包含玩家、敌人、道具等
        public const string ManualTiles = "ManualTiles"; // 手动绘制的瓦片层, 包含装饰性元素
        public const string ManualTiles2 = "ManualTiles2"; // 手动绘制的瓦片层, 包含装饰性元素
        public const string AutoLayer_MineBG = "AutoLayer_MineBG";
        public const string AutoTiles_BG_A = "AutoTiles_BG_A"; // 自动绘制的瓦片层, 包含地面、平台等
        public const string AutoTiles_BG_B = "AutoTiles_BG_B"; // 自动绘制的瓦片层, 包含地面、平台等
        public const string LogicMap = "LogicMap"; // 逻辑地图层, 0: Wall,
        public const string BGMap = "BGMap";

        // Entity Identifiers
        public const string Ae_SavePoint = "Ae_SavePoint"; // Save point, where store player's level progress.
        public const string Ae_MovePlatformer = "Ae_MovePlatformer";
        public const string Ae_MovePlatformerPathPoint = "Ae_MovePlatformerPathPoint";
        public const string Ae_CameraOverrideArea = "Ae_CameraOverrideArea";
        public const string Ae_SnakeHoney = "Ae_SnakeHoney";
        public const string Ae_SnakeDoor = "Ae_SnakeDoor";
        public const string Ae_LevelClearPoint = "Ae_LevelClearPoint";
        public const string Ae_Mat_Checkpoint = "Ae_Mat_Checkpoint";
        public const string Ae_Mat_Bee = "Ae_Mat_Bee";
        public const string Ae_Mat_ThornPlatform = "Ae_Mat_ThornPlatform";
        public const string Ae_Mat_Ore = "Ae_Mat_Ore";
        public const string Ae_Mat_Vine = "Ae_Mat_Vine";
        public const string Ae_Mat_Door = "Ae_Mat_Door";
        public const string Ae_ChangeBackgroundArea = "Ae_ChangeBackgroundArea";

        // Enum Identifiers
        public const string Enum_CameraMode = "CameraMode";

    }
    // csharpier-ignore-end
}
