name: ðŸš€ CI/CD æµæ°´çº¿

on:
  workflow_call:
    inputs:
      validDeployTargets:
        type: string
        required: true
        description: 'æœ‰æ•ˆçš„éƒ¨ç½²ç›®æ ‡åˆ—è¡¨(JSONå­—ç¬¦ä¸²)'
      buildTargets:
        type: string
        required: true
        description: 'æž„å»ºç›®æ ‡å¹³å°åˆ—è¡¨(JSONå­—ç¬¦ä¸²)'
      metadataConfig:
        type: string
        required: true
        description: 'å…ƒæ•°æ®é…ç½®(JSONå­—ç¬¦ä¸²)'
      testDataConfig:
        type: string
        required: true
        description: 'æµ‹è¯•æ•°æ®é…ç½®(JSONå­—ç¬¦ä¸²)'
      artifactConfig:
        type: string
        required: true
        description: 'æž„å»ºäº§ç‰©é…ç½®(JSONå­—ç¬¦ä¸²)'

permissions:
  contents: write

jobs:
  unpack_inputs:
    name: è§£åŒ…è¾“å…¥å‚æ•°
    runs-on: ubuntu-latest
    outputs:
      projectName: ${{ steps.unpack.outputs.projectName }}
      skipTests: ${{ steps.unpack.outputs.skipTests }}
      testsOnly: ${{ steps.unpack.outputs.testsOnly }}
      buildType: ${{ steps.unpack.outputs.buildType }}
      buildVersion: ${{ steps.unpack.outputs.buildVersion }}
      retentionDays: ${{ steps.unpack.outputs.retentionDays }}
      requiresCombined: ${{ steps.unpack.outputs.requiresCombined }}
      skipPerBuildTarget: ${{ steps.unpack.outputs.skipPerBuildTarget }}
      unityVersion: ${{ steps.unpack.outputs.unityVersion }}
      useGitLfs: ${{ steps.unpack.outputs.useGitLfs }}
      editModePath: ${{ steps.unpack.outputs.editModePath }}
      playModePath: ${{ steps.unpack.outputs.playModePath }}
      timeoutMinutesTests: ${{ steps.unpack.outputs.timeoutMinutesTests }}
      timeoutMinutesBuild: ${{ steps.unpack.outputs.timeoutMinutesBuild }}
      quietMode: ${{ steps.unpack.outputs.quietMode }}
    steps:
      - name: æ£€å‡ºé…ç½®æ–‡ä»¶
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/config/ci-defaults.json
          sparse-checkout-cone-mode: false
          fetch-depth: 1

      - id: unpack
        shell: bash
        run: |
          # è¯»å–è¾“å…¥å‚æ•°
          meta='${{ inputs.metadataConfig }}'
          artifact='${{ inputs.artifactConfig }}'
          testData='${{ inputs.testDataConfig }}'

          # å¦‚æžœå‚æ•°ä¸ºç©ºï¼Œåˆ™è¯»å–ci-defaults.json
          if [ -z "$meta" ] || [ "$meta" = "null" ] || [ "$meta" = "" ]; then
            meta=$(jq -c '.metadataConfig' .github/workflows/ci-defaults.json)
          fi
          if [ -z "$artifact" ] || [ "$artifact" = "null" ] || [ "$artifact" = "" ]; then
            artifact=$(jq -c '.artifactConfig' .github/workflows/ci-defaults.json)
          fi
          if [ -z "$testData" ] || [ "$testData" = "null" ] || [ "$testData" = "" ]; then
            testData=$(jq -c '.testDataConfig' .github/workflows/ci-defaults.json)
          fi

          # æµ‹è¯•æ•°æ®é…ç½®
          echo "unityVersion=$(echo "$testData" | jq -r .unityVersion)" >> "$GITHUB_OUTPUT"
          echo "useGitLfs=$(echo "$testData" | jq -r .useGitLfs)" >> "$GITHUB_OUTPUT"
          echo "editModePath=$(echo "$testData" | jq -r .editModePath)" >> "$GITHUB_OUTPUT"
          echo "playModePath=$(echo "$testData" | jq -r .playModePath)" >> "$GITHUB_OUTPUT"
          echo "quietMode=$(echo "$testData" | jq -r .quietMode)" >> "$GITHUB_OUTPUT"

          # å…ƒæ•°æ®é…ç½®
          echo "projectName=$(echo "$meta" | jq -r .projectName)" >> "$GITHUB_OUTPUT"
          echo "skipTests=$(echo "$meta" | jq -r .skipTests)" >> "$GITHUB_OUTPUT"
          echo "testsOnly=$(echo "$meta" | jq -r .testsOnly)" >> "$GITHUB_OUTPUT"
          echo "buildType=$(echo "$meta" | jq -r .buildType)" >> "$GITHUB_OUTPUT"
          echo "buildVersion=$(echo "$meta" | jq -r .buildVersion)" >> "$GITHUB_OUTPUT"
          echo "retentionDays=$(echo "$meta" | jq -r .retentionDays)" >> "$GITHUB_OUTPUT"
          echo "timeoutMinutesTests=$(echo "$meta" | jq -r .timeoutMinutesTests)" >> "$GITHUB_OUTPUT"
          echo "timeoutMinutesBuild=$(echo "$meta" | jq -r .timeoutMinutesBuild)" >> "$GITHUB_OUTPUT"

          # æž„å»ºäº§ç‰©é…ç½®
          echo "requiresCombined=$(echo "$artifact" | jq -r .requiresCombined)" >> "$GITHUB_OUTPUT"
          echo "skipPerBuildTarget=$(echo "$artifact" | jq -r .skipPerBuildTarget)" >> "$GITHUB_OUTPUT"

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # 1. è¿è¡Œæµ‹è¯•
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  run_tests:
    name: è¿è¡Œæµ‹è¯•
    if: ${{ needs.unpack_inputs.outputs.skipTests != 'true' }}
    needs: unpack_inputs
    uses: ./.github/workflows/step-1-test.yml
    with:
      unityVersion: ${{ needs.unpack_inputs.outputs.unityVersion }}
      useGitLfs: ${{ needs.unpack_inputs.outputs.useGitLfs }}
      editModePath: ${{ needs.unpack_inputs.outputs.editModePath }}
      playModePath: ${{ needs.unpack_inputs.outputs.playModePath }}
      timeoutMinutes: ${{ fromJson(needs.unpack_inputs.outputs.timeoutMinutesTests) }}
      quietMode: ${{ needs.unpack_inputs.outputs.quietMode }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # 2. æž„å»º
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  build:
    name: æž„å»º
    needs: 
      - unpack_inputs
      - run_tests
    if: >
      always() &&
      needs.unpack_inputs.outputs.testsOnly != 'true' &&
      (needs.run_tests.result == 'success' || needs.run_tests.result == 'skipped')
    uses: ./.github/workflows/step-2-build.yml
    with:
      projectName: ${{ needs.unpack_inputs.outputs.projectName }}
      unityVersion: ${{ needs.unpack_inputs.outputs.unityVersion }}
      buildVersion: ${{ needs.unpack_inputs.outputs.buildVersion }}
      buildType: ${{ needs.unpack_inputs.outputs.buildType }}
      buildTargets: ${{ inputs.buildTargets }}
      combineArtifacts: ${{ needs.unpack_inputs.outputs.requiresCombined }}
      timeoutMinutes: ${{ fromJson(needs.unpack_inputs.outputs.timeoutMinutesBuild) }}
      retentionDays: ${{ fromJson(needs.unpack_inputs.outputs.retentionDays) }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # 3. å‘å¸ƒ
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  release:
    name: å‘å¸ƒ
    needs: 
      - unpack_inputs
      - build
    if: > 
      always() &&
      needs.unpack_inputs.outputs.testsOnly != 'true' &&
      needs.build.result == 'success' && 
      (
        needs.unpack_inputs.outputs.buildType == 'release' || 
        needs.unpack_inputs.outputs.buildType == 'release_candidate'
      )
    uses: ./.github/workflows/step-3-release.yml
    with:
      buildType: ${{ needs.unpack_inputs.outputs.buildType }}
      buildVersion: ${{ needs.unpack_inputs.outputs.buildVersion }}
      projectName: ${{ needs.unpack_inputs.outputs.projectName }}
      buildTargets: ${{ inputs.buildTargets }}
      combineArtifacts: ${{ needs.unpack_inputs.outputs.requiresCombined }}
      skipPerBuildTargetArtifacts: ${{ needs.unpack_inputs.outputs.skipPerBuildTarget }}

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # 4. éƒ¨ç½²
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  deploy:
    name: éƒ¨ç½²
    needs: 
      - unpack_inputs
      - build
      - release
    if: > 
      always() &&
       needs.unpack_inputs.outputs.testsOnly != 'true' &&
       needs.release.result == 'success' &&
       inputs.validDeployTargets != '[]'
    uses: ./.github/workflows/step-4-deploy.yml
    with:
      buildType: ${{ needs.unpack_inputs.outputs.buildType }}
      buildVersion: ${{ needs.unpack_inputs.outputs.buildVersion }}
      projectName: ${{ needs.unpack_inputs.outputs.projectName }}
      deployTargets: ${{ inputs.validDeployTargets }}
      buildTargets: ${{ inputs.buildTargets }}
      hasCombinedArtifacts: ${{ needs.unpack_inputs.outputs.requiresCombined }}
      artifactSource: build
    secrets:
      CICD_PAT: ${{ secrets.CICD_PAT }}
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
      ITCH_USERNAME: ${{ secrets.ITCH_USERNAME }}
      ITCH_PROJECT: ${{ secrets.ITCH_PROJECT }}
      APPCENTER_OWNER_NAME: ${{ secrets.APPCENTER_OWNER_NAME }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
      STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
      STEAM_APP_ID: ${{ secrets.STEAM_APP_ID }}
      STEAM_DEPOT_VDF_PATH: ${{ secrets.STEAM_DEPOT_VDF_PATH }}
      APPSTORE_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
      APPSTORE_API_ISSUER_ID: ${{ secrets.APPSTORE_API_ISSUER_ID }}
      APPSTORE_API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
      CUSTOM_SERVER_HOST: ${{ secrets.CUSTOM_SERVER_HOST }}
      CUSTOM_SERVER_USER: ${{ secrets.CUSTOM_SERVER_USER }}
      CUSTOM_SERVER_KEY: ${{ secrets.CUSTOM_SERVER_KEY }}

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # 5. é€šçŸ¥
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  notify:
    name: é€šçŸ¥
    needs: 
      - unpack_inputs
      - run_tests
      - build
      - release
      - deploy
    if: > 
      always() && 
      needs.unpack_inputs.outputs.testsOnly != 'true' &&
      (
        needs.unpack_inputs.outputs.buildType == 'release' || 
        needs.unpack_inputs.outputs.buildType == 'release_candidate'
      )
    uses: ./.github/workflows/step-5-notify.yml
    with:
      buildVersion: ${{ needs.unpack_inputs.outputs.buildVersion }}
      releaseResult: ${{ needs.release.result }}
      releaseErrorMessage: ${{ needs.release.outputs.releaseErrorMessage }}
      deployResult: ${{ needs.deploy.result }}
      testsHasFails: ${{ needs.run_tests.outputs.hasFails }}
      testsTotal: ${{ needs.run_tests.outputs.totalTests }}
      testsPassed: ${{ needs.run_tests.outputs.passedTests }}
      testsFailedNames: ${{ needs.run_tests.outputs.failedTestNames }}
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}