name: ðŸ“„ æ±‡æ€»éƒ¨ç½²ç»“æžœ

description: |
  ä¸‹è½½éƒ¨ç½²ç»“æžœäº§ç‰©ï¼Œå¹¶å°†æ ¼å¼åŒ–çš„æ±‡æ€»å†™å…¥ GitHub ä½œä¸šæ‘˜è¦ã€‚

on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      buildVersion:
        required: true
        type: string
      buildType:
        required: true
        type: string

jobs:
  summarize:
    name: ðŸ“„ æ±‡æ€»éƒ¨ç½²ç»“æžœ
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ‘… ä¸‹è½½æ‰€æœ‰éƒ¨ç½²ç»“æžœæ–‡ä»¶
        uses: actions/download-artifact@v4
        with:
          pattern: deployment-results-*
          path: deployment-results
          merge-multiple: true

      - name: ðŸ“œ å†™å…¥éƒ¨ç½²æ±‡æ€»
        run: |
          if ! ls deployment-results/*.json 1> /dev/null 2>&1; then
            echo "âš ï¸ æœªæ‰¾åˆ°ä»»ä½•éƒ¨ç½²ç»“æžœæ–‡ä»¶ã€‚"
            echo "æ²¡æœ‰å¯æ±‡æ€»çš„éƒ¨ç½²ç»“æžœæ–‡ä»¶ã€‚" >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

          echo "### ðŸŒ éƒ¨ç½²ç»“æžœæ±‡æ€»" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "**é¡¹ç›®:** \`${{ inputs.projectName }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**æž„å»ºç±»åž‹:** \`${{ inputs.buildType }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**æž„å»ºç‰ˆæœ¬:** \`${{ inputs.buildVersion }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**éƒ¨ç½²æ—¶é—´:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "| ç›®æ ‡ | çŠ¶æ€ | è¯¦æƒ… |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|--------|---------|" >> $GITHUB_STEP_SUMMARY

          for file in deployment-results/*.json; do
            TARGET=$(basename "$file" .json)
            STATUS=$(jq -r '.status' "$file")
            NOTE=$(jq -r '.note' "$file")

            echo "| $TARGET | $STATUS | $NOTE |" >> $GITHUB_STEP_SUMMARY
          done