name: ðŸ“„ æ±‡æ€»å…ƒæ•°æ®

description: |
  å°†è§£æžåŽçš„æž„å»ºå…ƒæ•°æ®æ±‡æ€»å†™å…¥ GitHub ä½œä¸šæ‘˜è¦ã€‚

on:
  workflow_call:
    inputs:
      useGitLfs:
        required: true
        type: string
      quietMode:
        required: true
        type: string
      excludeUnityTests:
        required: true
        type: string
      forceCombineArtifacts:
        required: true
        type: string
      projectName:
        required: true
        type: string
      playModePath:
        required: true
        type: string
      editModePath:
        required: true
        type: string
      unityVersion:
        required: true
        type: string
      buildVersion:
        required: true
        type: string
      buildType:
        required: true
        type: string
      skipTests:
        required: true
        type: string
      testsOnly:
        required: true
        type: string
      retentionDays:
        required: true
        type: string
      timeoutMinutesTests:
        required: true
        type: string
      timeoutMinutesBuild:
        required: true
        type: string
      buildTargets:
        required: true
        type: string
      validDeployTargets:
        required: true
        type: string
      requiresCombined:
        required: true
        type: string
      skipPerBuildTarget:
        required: true
        type: string

jobs:
  summarize:
    name: ðŸ“„ æ±‡æ€»å…ƒæ•°æ®
    runs-on: ubuntu-latest
    steps:
      - name: å†™å…¥æ±‡æ€»
        run: |
          BUILD_TARGETS=$(echo '${{ inputs.buildTargets }}' | jq -c '.')
          DEPLOY_TARGETS=$(echo '${{ inputs.validDeployTargets }}' | jq -c '.')
      
          if [[ -z "$DEPLOY_TARGETS" || "$DEPLOY_TARGETS" == 'null' ]]; then
            DEPLOY_TARGETS='[]'
          fi
      
          if [[ -z "$BUILD_TARGETS" || "$BUILD_TARGETS" == 'null' ]]; then
            BUILD_TARGETS='[]'
          fi
      
          echo "# â³ æœ€ç»ˆå…ƒæ•°æ®æ±‡æ€»" >> $GITHUB_STEP_SUMMARY

          echo "## âš™ï¸ CI é€‰é¡¹æ±‡æ€»" >> $GITHUB_STEP_SUMMARY
          echo "| é€‰é¡¹                  | å€¼ |" >> $GITHUB_STEP_SUMMARY
          echo "|-------------------------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| ä½¿ç”¨ Git LFS             | ${{ inputs.useGitLfs }} |" >> $GITHUB_STEP_SUMMARY
          echo "| é™é»˜æ¨¡å¼              | ${{ inputs.quietMode }} |" >> $GITHUB_STEP_SUMMARY
          echo "| è·³è¿‡ Unity æµ‹è¯•        | ${{ inputs.excludeUnityTests }} |" >> $GITHUB_STEP_SUMMARY
          echo "| å¼ºåˆ¶åˆå¹¶äº§ç‰© | ${{ inputs.forceCombineArtifacts }} |" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
      
          echo "## ðŸ“‹ æµ‹è¯•é…ç½®æ±‡æ€»" >> "$GITHUB_STEP_SUMMARY"
          echo "| é”®             | å€¼                      |" >> "$GITHUB_STEP_SUMMARY"
          echo "|-----------------|----------------------------|" >> "$GITHUB_STEP_SUMMARY"
          echo "| EditMode è·¯å¾„   | ${{ inputs.editModePath }} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| PlayMode è·¯å¾„   | ${{ inputs.playModePath }} |" >> "$GITHUB_STEP_SUMMARY"

          echo "" >> $GITHUB_STEP_SUMMARY

          echo "## ðŸ“‹ æž„å»ºä¸Žéƒ¨ç½²å…ƒæ•°æ®" >> $GITHUB_STEP_SUMMARY
          echo "| é”®                          | å€¼ |" >> $GITHUB_STEP_SUMMARY
          echo "|------------------------------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Unity ç‰ˆæœ¬                | ${{ inputs.unityVersion }} |" >> $GITHUB_STEP_SUMMARY
          echo "| é¡¹ç›®åç§°                 | ${{ inputs.projectName }} |" >> $GITHUB_STEP_SUMMARY
          echo "| è·³è¿‡æµ‹è¯•                   | ${{ inputs.skipTests }} |" >> $GITHUB_STEP_SUMMARY
          echo "| ä»…æµ‹è¯•                   | ${{ inputs.testsOnly }} |" >> $GITHUB_STEP_SUMMARY
          echo "| æµ‹è¯•è¶…æ—¶ï¼ˆåˆ†é’Ÿï¼‰      | ${{ inputs.timeoutMinutesTests }} |" >> $GITHUB_STEP_SUMMARY
          echo "| æž„å»ºè¶…æ—¶ï¼ˆåˆ†é’Ÿï¼‰      | ${{ inputs.timeoutMinutesBuild }} |" >> $GITHUB_STEP_SUMMARY
          echo "| æž„å»ºç‰ˆæœ¬                | ${{ inputs.buildVersion }} |" >> $GITHUB_STEP_SUMMARY
          echo "| æž„å»ºç±»åž‹                   | ${{ inputs.buildType }} |" >> $GITHUB_STEP_SUMMARY
          echo "| æž„å»ºç›®æ ‡                | \`$BUILD_TARGETS\` |" >> $GITHUB_STEP_SUMMARY
          echo "| éƒ¨ç½²ç›®æ ‡               | \`$DEPLOY_TARGETS\` |" >> $GITHUB_STEP_SUMMARY
          echo "| ä¿ç•™å¤©æ•°               | ${{ inputs.retentionDays }} |" >> $GITHUB_STEP_SUMMARY
          echo "| æ˜¯å¦éœ€è¦åˆå¹¶äº§ç‰©  | ${{ inputs.requiresCombined }} |" >> $GITHUB_STEP_SUMMARY
          echo "| è·³è¿‡æ¯æž„å»ºç›®æ ‡äº§ç‰© | ${{ inputs.skipPerBuildTarget }} |" >> $GITHUB_STEP_SUMMARY